const mongoose = require("mongoose");

const formSchema = new mongoose.Schema(
  {
    user_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    title: { type: String, required: true },
    locked: { type: Boolean, default: false },
    description: { type: String },
    visibility: {
      type: String,
      enum: ["public", "private"],
      default: "private",
    },
    publicUrl: { type: String, default: null },
    privateUrl: { type: String, default: null },
    theme: { type: String },
    fields: [
      {
        type: {
          type: String,
          required: true,
          enum: [
            "text",
            "textarea",
            "number",
            "tel",
            "checkbox-group",
            "radio-group",
            "button",
            "select",
            "date",
            "file",
            "header",
            "paragraph",
            "autocomplete",
            "hidden",
            "starRating",
          ],
        },
        subtype: {
          type: String,
          enum: [
            "text",
            "password",
            "email",
            "tel",
            "url",
            "number",
            "date",
            "datetime-local",
            "month",
            "week",
            "time",
            "color",
            "search",
            "submit",
            "reset",
            "file",
            "hidden",
          ],
        },
        label: { type: String, required: true },
        name: { type: String, required: true },
        placeholder: { type: String },
        className: { type: String },
        style: { type: String },
        required: { type: Boolean, default: false },
        options: [
          {
            label: { type: String, required: true },
            value: { type: String, required: true },
            selected: { type: Boolean, default: false },
          },
        ],
        description: { type: String },
        access: { type: [String], default: ["all"] },
        values: { type: mongoose.Schema.Types.Mixed },
        value: { type: mongoose.Schema.Types.Mixed },
        multiple: { type: Boolean, default: false },
        inline: { type: Boolean, default: false },
        min_length: { type: Number },
        max_length: { type: Number },
        min: { type: mongoose.Schema.Types.Mixed },
        max: { type: mongoose.Schema.Types.Mixed },
        toggle: { type: Boolean },
        other: { type: Boolean },
        maxlength: { type: Number },
        rows: { type: Number },
        step: { type: Number },
        style: { type: String },
        tooltip: { type: String },
        visibility_rules: { type: mongoose.Schema.Types.Mixed },
        order: { type: Number, required: false },
      },
    ],
    fieldStyles: {
      type: Map,
      of: {
        backgroundColor: { type: String, default: "#ffffff" },
        color: { type: String, default: "#000000" },
        position: {
          type: String,
          enum: ["left", "center", "right"],
          default: "left",
        },
      },
      default: {},
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Form", formSchema);
